=== konstpie/Laboratorium/Lab 2/sklep.dtd
<!ELEMENT sklep (produkt+)>
<!ELEMENT produkt (nazwa, cena, kategoria)>
<!ATTLIST produkt id ID #REQUIRED>
<!ELEMENT nazwa (#PCDATA)>
<!ELEMENT cena (#PCDATA)>
<!ATTLIST cena waluta CDATA #REQUIRED>
<!ELEMENT kategoria (#PCDATA)>

=== konstpie/Laboratorium/Lab 2/sklep.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sklep SYSTEM "sklep.dtd">
<sklep>
    <produkt id="p1">
        <nazwa>MacBook Air</nazwa>
        <cena waluta="PLN">5000</cena>
        <kategoria>Laptopy</kategoria>
    </produkt>
    <produkt id="p2">
        <nazwa>iPhone 15</nazwa>
        <cena waluta="PLN">4000</cena>
        <kategoria>Smartfony</kategoria>
    </produkt>
</sklep>
